### ISSUE TITLE
Video player does not follow redirects

### ISSUE THREAD

**Issue by luthor112** [flexbooru/flexbooru#178]
**Describe the bug**
Video player does not follow redirects.

**To Reproduce**
1. Find a video where large_file_url points to a redirect
2. Click on it
3. Video doesn't load

**Expected behavior**
Video player should follow redirects and play from the new URL.

**Comment by luthor112** [comment]
Fixed in 3.0.3.c1249

**Comment by mangkoran** [comment]
It seems that this issue still kind of persist 3.0.8.c1275. There are some file_url.zip (mostly i.pximg.net) that won't load, while others file_url.zip will load. I don't think the file size is related, because some video (with .zip url) around 5 MB will load, while other video with smaller size won't.
